### ISSUE TITLE
TypeError: css.walk is not a function

### ISSUE THREAD

**Issue by VaniaFed** [NMFR/optimize-css-assets-webpack-plugin#108]
(node:19509) UnhandledPromiseRejectionWarning: TypeError: css.walk is not a function
    at css (/home/vaniafed/Документы/projects/web/webpack/node_modules/postcss-discard-comments/dist/index.js:67:13)
    at initializePlugin (/home/vaniafed/Документы/projects/web/webpack/node_modules/cssnano/dist/index.js:31:51)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
(node:19509) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19509) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by NMFR** [comment]
Closing it, I dont think this is a optimize-css-assets-webpack-plugin issue. 

Please comment if you still it is, and provide the node version, npm and a code sample so i can reproduce the error.
