### ISSUE TITLE
 Cannot find module 'is-obj'

### ISSUE THREAD

**Issue by herrvigg** [NMFR/optimize-css-assets-webpack-plugin#132]
If i run an npm audit fix i get this error: Cannot find module 'is-obj'.
I'm not sure about the exact reason but it seems this comes from a sub-dependency `postcss-minify-selectors` and an old version of css-nano. Since there is no update here since 2019 (is this repo still alive ? #131) i suspect this plugin is pointing to obsolete versions.

Also there is this warning: caniuse-lite is outdated. 

```
92% chunk asset optimization OptimizeCssAssetsWebpackPluginBrowserslist: caniuse-lite is outdated. Please run next command `npm update`
Error: Cannot find module 'is-obj'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (/d/projects/wp-psionic/wp-content/themes/psionicstorm/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/d/projects/wp-psionic/wp-content/themes/psionicstorm/node_modules/dot-prop/index.js:2:15)
    at Module._compile (/d/projects/wp-psionic/wp-content/themes/psionicstorm/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (/d/projects/wp-psionic/wp-content/themes/psionicstorm/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/d/projects/wp-psionic/wp-content/themes/psionicstorm/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/parser.js:7:16)
    at Module._compile (/d/projects/wp-psionic/wp-content/themes/psionicstorm/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (/d/projects/wp-psionic/wp-content/themes/psionicstorm/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/d/projects/wp-psionic/wp-content/themes/psionicstorm/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/processor.js:5:15)
    at Module._compile (/d/projects/wp-psionic/wp-content/themes/psionicstorm/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (/d/projects/wp-psionic/wp-content/themes/psionicstorm/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/d/projects/wp-psionic/wp-content/themes/psionicstorm/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/index.js:5:18)
    at Module._compile (/d/projects/wp-psionic/wp-content/themes/psionicstorm/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
```

**Comment by NMFR** [comment]
Just releases 5.0.4 with some dependency updates, does it still happen on that version?

If yes could i get a node version and sample code to replicate the issue please?

**Comment by AlonsoK28** [comment]
Same for me 

I just updated my project dependencies yesterday using `npm update ` and now I can't generate the production bundle 

```

**Comment by AlonsoK28** [comment]
Same for me 

I just updated my project dependencies yesterday using `npm update ` and now I can't generate the production bundle 

Compiling using **Node.JS 12.16.1**
```
Error: Cannot find module 'is-obj'
Require stack:
- C:\xampp\htdocs\xadani\node_modules\dot-prop\index.js
- C:\xampp\htdocs\xadani\node_modules\postcss-minify-selectors\node_modules\postcss-selector-parser\dist\parser.js
- C:\xampp\htdocs\xadani\node_modules\postcss-minify-selectors\node_modules\postcss-selector-parser\dist\processor.js
- C:\xampp\htdocs\xadani\node_modules\postcss-minify-selectors\node_modules\postcss-selector-parser\dist\index.js
- C:\xampp\htdocs\xadani\node_modules\postcss-minify-selectors\dist\index.js
- C:\xampp\htdocs\xadani\node_modules\cssnano-preset-default\dist\index.js
- C:\xampp\htdocs\xadani\node_modules\cssnano\dist\index.js
- C:\xampp\htdocs\xadani\webpack.prod.js
- C:\xampp\htdocs\xadani\node_modules\webpack-cli\bin\utils\convert-argv.js
- C:\xampp\htdocs\xadani\node_modules\webpack-cli\bin\cli.js
- C:\xampp\htdocs\xadani\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (C:\xampp\htdocs\xadani\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (C:\xampp\htdocs\xadani\node_modules\dot-prop\index.js:2:15)
    at Module._compile (C:\xampp\htdocs\xadani\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (C:\xampp\htdocs\xadani\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (C:\xampp\htdocs\xadani\node_modules\postcss-minify-selectors\node_modules\postcss-selector-parser\dist\parser.js:7:16)
    at Module._compile (C:\xampp\htdocs\xadani\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (C:\xampp\htdocs\xadani\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (C:\xampp\htdocs\xadani\node_modules\postcss-minify-selectors\node_modules\postcss-selector-parser\dist\processor.js:5:15)
    at Module._compile (C:\xampp\htdocs\xadani\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (C:\xampp\htdocs\xadani\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (C:\xampp\htdocs\xadani\node_modules\postcss-minify-selectors\node_modules\postcss-selector-parser\dist\index.js:5:18)
    at Module._compile (C:\xampp\htdocs\xadani\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (C:\xampp\htdocs\xadani\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (C:\xampp\htdocs\xadani\node_modules\postcss-minify-selectors\dist\index.js:17:30)
    at Module._compile (C:\xampp\htdocs\xadani\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xadani@2.5.3 prod: `webpack --config webpack.prod.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xadani@2.5.3 prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```


Compiling using **Node.JS v10.20.0**
```
Error: Cannot find module 'is-obj'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (C:\xampp\htdocs\xadani\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (C:\xampp\htdocs\xadani\node_modules\dot-prop\index.js:2:15)
    at Module._compile (C:\xampp\htdocs\xadani\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (C:\xampp\htdocs\xadani\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (C:\xampp\htdocs\xadani\node_modules\postcss-minify-selectors\node_modules\postcss-selector-parser\dist\parser.js:7:16)
    at Module._compile (C:\xampp\htdocs\xadani\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (C:\xampp\htdocs\xadani\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (C:\xampp\htdocs\xadani\node_modules\postcss-minify-selectors\node_modules\postcss-selector-parser\dist\processor.js:5:15)
    at Module._compile (C:\xampp\htdocs\xadani\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (C:\xampp\htdocs\xadani\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (C:\xampp\htdocs\xadani\node_modules\postcss-minify-selectors\node_modules\postcss-selector-parser\dist\index.js:5:18)
    at Module._compile (C:\xampp\htdocs\xadani\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (C:\xampp\htdocs\xadani\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xadani@2.5.3 prod: `webpack --config webpack.prod.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xadani@2.5.3 prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
You know when this will be fixed?

**Comment by kamaloush** [comment]
For me, the resolution is: delete node_modules folder and run npm install.

**Comment by NMFR** [comment]
Any chance i can get a sample code to replicate this issue?

**Comment by kamaloush** [comment]
Yep, maby usefull, notice i can't reproduce anymore:
packages.json before npm update :
`{
  "name": "evue",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "description": "eVue",
  "author": {
    "name": ""
  },
  "dependencies": {
    "axios": "^0.19.0",
    "bootstrap-vue": "^2.0.3",
    "moment": "^2.24.0",
    "vue": "^2.6.10",
    "vue-loader": "^15.7.1",
    "vue-router": "^3.1.3",
    "vue-template-compiler": "^2.6.10",
    "vuetify": "^1.5.18",
    "vuetify-upload-button": "^2.0.2"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "3.0.4",
    "@vue/cli-plugin-eslint": "3.0.4",
    "@vue/cli-service": "3.0.4",
    "eslint": "5.6.0",
    "eslint-plugin-vue": "4.7.1",
    "sass-loader": "^7.3.1"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "rules": {},
    "parserOptions": {
      "parser": "babel-eslint"
    }
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}
` #

after npm update / npm install vuetify@latest / npm install vue@latest / npm audit fix:
`{
  "name": "evue",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "description": "eVue",
  "author": {
    "name": ""
  },
  "dependencies": {
    "axios": "^0.19.2",
    "bootstrap-vue": "^2.2.2",
    "moment": "^2.24.0",
    "vue": "^2.6.11",
    "vue-loader": "^15.8.3",
    "vue-router": "^3.1.5",
    "vue-template-compiler": "^2.6.11",
    "vuetify": "^1.5.22",
    "vuetify-upload-button": "^2.0.2"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "3.0.4",
    "@vue/cli-plugin-eslint": "3.0.4",
    "@vue/cli-service": "3.0.4",
    "eslint": "5.6.0",
    "eslint-plugin-vue": "4.7.1",
    "sass-loader": "^7.3.1"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "rules": {},
    "parserOptions": {
      "parser": "babel-eslint"
    }
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}
`

**Comment by herrvigg** [comment]
With 5.0.4 it works now! So i close this ticket.

With 5.0.3 i had this error only after running `npm audit fix` but it worked before running this so it was certainly some sub dependency. I can't provide you the code but for information here were the direct dependencies.
```
  "devDependencies": {
    "@babel/core": "^7.11.4",
    "@babel/preset-env": "^7.11.0",
    "@babel/preset-react": "^7.10.4",
    "babel-loader": "^8.1.0",
    "clean-webpack-plugin": "^3.0.0",
    "css-loader": "^4.2.2",
    "file-loader": "^6.0.0",
    "mini-css-extract-plugin": "^0.10.0",
    "optimize-css-assets-webpack-plugin": "^5.0.3",
    "webpack": "^4.44.1",
    "webpack-cli": "^3.3.12"
  },
  "dependencies": {
    "animate.css": "^4.1.0",
    "d3": "^5.16.0",
    "react": "^16.13.1",
    "react-app-polyfill": "^1.0.6",
    "react-dom": "^16.13.1",
    "react-flip-toolkit": "^7.0.12",
    "select2": "^4.0.13",
    "sorttable": "^1.0.2"
  }
```

**Comment by wasimTQ** [comment]
> For me, the resolution is: delete node_modules folder and run npm install.

Yes, Really working for me

**Comment by kenmallar** [comment]
> For me, the resolution is: delete node_modules folder and run npm install.

Same here. Worked for me.

**Comment by connect-dips** [comment]
> For me, the resolution is: delete node_modules folder and run npm install.

Ultimate solution!. Worked for me.

**Comment by wcyoyo44** [comment]
> With 5.0.4 it works now! So i close this ticket.
> 
> With 5.0.3 i had this error only after running `npm audit fix` but it worked before running this so it was certainly some sub dependency. I can't provide you the code but for information here were the direct dependencies.
> 
> ```
>   "devDependencies": {
>     "@babel/core": "^7.11.4",
>     "@babel/preset-env": "^7.11.0",
>     "@babel/preset-react": "^7.10.4",
>     "babel-loader": "^8.1.0",
>     "clean-webpack-plugin": "^3.0.0",
>     "css-loader": "^4.2.2",
>     "file-loader": "^6.0.0",
>     "mini-css-extract-plugin": "^0.10.0",
>     "optimize-css-assets-webpack-plugin": "^5.0.3",
>     "webpack": "^4.44.1",
>     "webpack-cli": "^3.3.12"
>   },
>   "dependencies": {
>     "animate.css": "^4.1.0",
>     "d3": "^5.16.0",
>     "react": "^16.13.1",
>     "react-app-polyfill": "^1.0.6",
>     "react-dom": "^16.13.1",
>     "react-flip-toolkit": "^7.0.12",
>     "select2": "^4.0.13",
>     "sorttable": "^1.0.2"
>   }
> ```

Reinstalling optimize-css-assets-webpack-plugin (which also happened to go from 5.0.3 to 5.0.4 for me too) worked for me.

Took me a moment to figure out what the issue might be and what to try, but I too had done `npm audit fix` while installing something else previously so I also suspect it's not this plugin v5.0.3, but something else like a sub dependency since I didn't have a problem until after as well.
