### ISSUE TITLE
Compatibility problem with webpack@3.6

### ISSUE THREAD

**Issue by yugasun** [NMFR/optimize-css-assets-webpack-plugin#38]
When I install `optimize-css-assets-webpack-plugin@4.0`，my project will build failed, below is the errors.

```bash
⠋ building for production.../Users/Yuga/Desktop/Developing/compass/node_modules/last-call-webpack-plugin/src/index.js:170
    compiler.hooks.compilation.tap(
                   ^

TypeError: Cannot read property 'compilation' of undefined
    at OptimizeCssAssetsWebpackPlugin.apply (/Users/Yuga/Desktop/Developing/compass/node_modules/last-call-webpack-plugin/src/index.js:170:20)
    at Compiler.apply (/Users/Yuga/Desktop/Developing/compass/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/Users/Yuga/Desktop/Developing/compass/node_modules/webpack/lib/webpack.js:33:19)
    at err (/Users/Yuga/Desktop/Developing/compass/build/build.js:19:3)
    at next (/Users/Yuga/Desktop/Developing/compass/node_modules/rimraf/rimraf.js:75:7)
    at FSReqWrap.CB [as oncomplete] (/Users/Yuga/Desktop/Developing/compass/node_modules/rimraf/rimraf.js:111:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

this is part of my `package.json`:

```js
"optimize-css-assets-webpack-plugin": "^4.0.0",
"webpack": "^3.6.0",
```

**Comment by NMFR** [comment]
The v4.0.0 of `optimize-css-assets-webpack-plugin` requires `webpack` v4.

**Comment by yugasun** [comment]
@NMFR Many thanks, I have read your source code, and found the reason, so I changed `optimize-css-assets-webpack-plugin` to `3.2.0`.

**Comment by edmorley** [comment]
> The v4.0.0 of optimize-css-assets-webpack-plugin requires webpack v4.

I see `optimize-css-assets-webpack-plugin` doesn't have a `peerDependency` on webpack at the moment. If one were added, it might prevent confusion for cases like this? :-)

**Comment by sayhitoarvind** [comment]
yeah I had this issue as well. Changed to 3.2.0 as Yugasun mentioned. Thanks

**Comment by NMFR** [comment]
`peerDependency` added, thanks for the suggestion @edmorley  :)
