### ISSUE TITLE
Issues with { cssProcessorOptions: { safe: true } } on 5.0.0

### ISSUE THREAD

**Issue by lehni** [NMFR/optimize-css-assets-webpack-plugin#65]
I tried to update to 5.0.0, but building now throws this error:

```
UnhandledPromiseRejectionWarning: Error: Option safe was removed. Use parser: require("postcss-safe-parser")
    at parse (.../node_modules/postcss/lib/parse.js:18:15)
    at new LazyResult (.../node_modules/postcss/lib/lazy-result.js:70:24)
    at Processor.process (.../node_modules/postcss/lib/processor.js:117:12)
    at Function.creator.process (.../node_modules/postcss/lib/postcss.js:165:43)
    at OptimizeCssAssetsWebpackPlugin.processCss (.../node_modules/optimize-css-assets-webpack-plugin/src/index.js:62:21)
    at Object.processor (.../node_modules/optimize-css-assets-webpack-plugin/src/index.js:11:18)
    at each (.../node_modules/last-call-webpack-plugin/src/index.js:150:10)
    at arrayEach (.../node_modules/lodash/_arrayEach.js:15:9)
    at forEach (.../node_modules/lodash/forEach.js:38:10)
    at OptimizeCssAssetsWebpackPlugin.process (.../node_modules/last-call-webpack-plugin/src/index.js:147:5)
    at compilation.hooks.optimizeChunkAssets.tapPromise.chunks (.../node_modules/last-call-webpack-plugin/src/index.js:178:28)
    at _err0 (eval at create (.../node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:13:1)
    at .../node_modules/uglifyjs-webpack-plugin/dist/index.js:282:11
    at step (.../node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:90:11)
    at done (.../node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:99:22)
    at .../node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:105:15
```

**Comment by NMFR** [comment]
`cssnano` issue.

Can you try this: https://github.com/cssnano/cssnano/issues/119#issuecomment-182855568

**Comment by NMFR** [comment]
On `optimize-css-assets-webpack-plugin@5.0.0` we updated `cssnano` to v4. That's why the error is occurring.

The solution from https://github.com/cssnano/cssnano/issues/119#issuecomment-182855568 (comment) did not work?

**Comment by jsparedes** [comment]
Maybe, the cause is relative to [the difference in safe option between v3 and v4](https://github.com/cssnano/cssnano/issues/358) in cssnano. One of these default changes would be the problem.

To work with `optimize-css-assets-webpack-plugin@5.0.0` 
```javascript
const safeParser = require('postcss-safe-parser');

new OptimizeCssAssetsPlugin({
        cssProcessorOptions: { 
          parser: safeParser,
          discardComments: {
            removeAll: true
          }
        }
      })
```
