### ISSUE TITLE
Build failing for Production mode webpack@4.16.3

### ISSUE THREAD

**Issue by akash2016** [NMFR/optimize-css-assets-webpack-plugin#97]
The build is running as expected in dev mode but fails in production mode.
Configuration:
`  optimization: {
    minimizer: [
      new UglifyJsPlugin({
        cache: true,
        parallel: true,
      }),
      new OptimizeCSSAssetsPlugin({}),
    ],
  },`

Error:
`JisonLexerError: Lexical error on line 1: Unrecognized text.

  Erroneous area:
1: width * 1.75
^..^
    at /Users/evive/IdeaProjects/CampaignsFrontEnd/campaigns-frontend/css/myevive-4592690b255cd15c7dbd.min.css:3961:5
    at Object.parseError (/Users/evive/IdeaProjects/CampaignsFrontEnd/node_modules/cssnano-preset-default/node_modules/postcss-calc/dist/parser.js:1164:15)
    at Object.lexer_parseError [as parseError] (/Users/evive/IdeaProjects/CampaignsFrontEnd/node_modules/cssnano-preset-default/node_modules/postcss-calc/dist/parser.js:2297:44)
    at Object.lexer_next [as next] (/Users/evive/IdeaProjects/CampaignsFrontEnd/node_modules/cssnano-preset-default/node_modules/postcss-calc/dist/parser.js:3292:22)
    at Object.lexer_fastLex [as fastLex] (/Users/evive/IdeaProjects/CampaignsFrontEnd/node_modules/cssnano-preset-default/node_modules/postcss-calc/dist/parser.js:3367:18)
    at fastLex (/Users/evive/IdeaProjects/CampaignsFrontEnd/node_modules/cssnano-preset-default/node_modules/postcss-calc/dist/parser.js:1567:27)
    at Parser.parse (/Users/evive/IdeaProjects/CampaignsFrontEnd/node_modules/cssnano-preset-default/node_modules/postcss-calc/dist/parser.js:1641:30)
    at /Users/evive/IdeaProjects/CampaignsFrontEnd/node_modules/cssnano-preset-default/node_modules/postcss-calc/dist/lib/transform.js:30:30
    at walk (/Users/evive/IdeaProjects/CampaignsFrontEnd/node_modules/postcss-value-parser/lib/walk.js:19:7)
    at ValueParser.walk (/Users/evive/IdeaProjects/CampaignsFrontEnd/node_modules/postcss-value-parser/lib/index.js:18:3)
    at transformValue (/Users/evive/IdeaProjects/CampaignsFrontEnd/node_modules/cssnano-preset-default/node_modules/postcss-calc/dist/lib/transform.js:24:50)
    at _default (/Users/evive/IdeaProjects/CampaignsFrontEnd/node_modules/cssnano-preset-default/node_modules/postcss-calc/dist/lib/transform.js:59:100)
    at /Users/evive/IdeaProjects/CampaignsFrontEnd/node_modules/cssnano-preset-default/node_modules/postcss-calc/dist/index.js:25:51
    at /Users/evive/IdeaProjects/CampaignsFrontEnd/node_modules/postcss/lib/container.js:135:18
    at Rule.each (/Users/evive/IdeaProjects/CampaignsFrontEnd/node_modules/postcss/lib/container.js:101:16)
    at Rule.walk (/Users/evive/IdeaProjects/CampaignsFrontEnd/node_modules/postcss/lib/container.js:131:17)
    at /Users/evive/IdeaProjects/CampaignsFrontEnd/node_modules/postcss/lib/container.js:148:24
    at AtRule.each (/Users/evive/IdeaProjects/CampaignsFrontEnd/node_modules/postcss/lib/container.js:101:16)
    at AtRule.walk (/Users/evive/IdeaProjects/CampaignsFrontEnd/node_modules/postcss/lib/container.js:131:17)
    at /Users/evive/IdeaProjects/CampaignsFrontEnd/node_modules/postcss/lib/container.js:148:24
    at Root.each (/Users/evive/IdeaProjects/CampaignsFrontEnd/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (/Users/evive/IdeaProjects/CampaignsFrontEnd/node_modules/postcss/lib/container.js:131:17)
    at /Users/evive/IdeaProjects/CampaignsFrontEnd/node_modules/cssnano-preset-default/node_modules/postcss-calc/dist/index.js:23:9
    at initializePlugin (/Users/evive/IdeaProjects/CampaignsFrontEnd/node_modules/optimize-css-assets-webpack-plugin/node_modules/cssnano/dist/index.js:31:51)
    at <anonymous>
`

**Comment by bradley-varol** [comment]
I have the same issue - my production build is failing when trying to parse `calc(~"100% - 49px")`:
```
JisonLexerError: Lexical error on line 1: Unrecognized text.

  Erroneous area:
1: ~"100% - 49px"
^..^
    at C:\assets\css\temp.css:14618:3
```

**Comment by NMFR** [comment]
Not a `optimize-css-assets-webpack-plugin` it can be a `cssnano` issue if you are using the default css processor.

**Comment by velkymx** [comment]
What is the fix???
